supplements = [
    "1,3-Dimethylamylamine",
    "5-HTP",
    "7-Keto DHEA",
    "7,8-Dihydroxyflavone",
    "African Mango",
    "Agmatine",
    "Akarkara",
    "Alanine",
    "Alanylglutamine",
    "Alcohol",
    "Aloe Vera",
    "Alpha-GPC",
    "Alpha-Ketoglutarate",
    "Alpha-Linolenic Acid (ALA)",
    "Alpha-Lipoic Acid",
    "Althaea Officinalis",
    "Amla",
    "Anatabine",
    "Aniracetam",
    "Apigenin",
    "Arachidonic Acid",
    "Arginine",
    "Arnica",
    "Artemisia Annua",
    "Artichoke Extract",
    "Asafoetida",
    "Ashwagandha",
    "Aspartate",
    "Astaxanthin",
    "Astragalus",
    "B Vitamins",
    "Baby Formula",
    "Bacopa Monnieri",
    "Baikal Skullcap",
    "Bakuchi",
    "Banaba Leaf",
    "Banana Flower",
    "Beef Protein",
    "Benfotiamine",
    "Berberine",
    "Beta-Alanine",
    "Beta-Carotene",
    "Beta-Glucans",
    "Betaine",
    "Betalains",
    "Bhringaraj",
    "Biotic Supplement",
    "Biotin (Vitamin B7)",
    "Bitter Cucumber",
    "Bitter Orange",
    "Black Barberry Extract",
    "Black Chokeberry",
    "Black Cohosh",
    "Black Currant",
    "Black Garlic Extract",
    "Black Ginger",
    "Black Pepper",
    "Black Seed",
    "Bladderwrack",
    "Boron",
    "Boswellia",
    "BPC-157",
    "Branched-Chain Amino Acids",
    "Brassaiopsis Glomerulata",
    "Brassinosteroids",
    "Bromelain",
    "Brown Seaweed Extract",
    "Bulbine Natalensis",
    "Burning Bush",
    "Bushman's Hat",
    "Butcher's Broom",
    "Butea Monosperma",
    "Butea Superba",
    "Butterfly Pea",
    "Caesalpinia Benthamiana",
    "Caffeine",
    "Calcium",
    "Calcium Caseinate",
    "Calcium-D-Glucarate",
    "Calendula Officinalis",
    "California Poppy",
    "Calorie-Blocker",
    "Cangfu Daotan Decoction",
    "Cannabidiol (CBD)",
    "Cannabis",
    "Capsaicin",
    "Capsicum Carotenoids",
    "Caralluma Fimbriata",
    "Carnosine",
    "Casein",
    "Cat's Claw",
    "Cat's Whiskers",
    "CDP-Choline",
    "Celastrus Paniculatus",
    "Celery Seed Extract",
    "Centrophenoxine",
    "Chaga",
    "Chaihu Longgu Muli Decoction",
    "Charcoal",
    "Chaste Tree",
    "Cherry Extract",
    "Chia Seeds",
    "China Rose",
    "Chinese Hawthorn",
    "Chinese Juniper",
    "Chinese Sweet Leaf",
    "Chitosan",
    "Chlorella",
    "Chlorogenic Acid",
    "Chlorophyll",
    "Choline",
    "Cholinergic",
    "Chondroitin",
    "Chromium",
    "Chrysin",
    "Cinnamon",
    "Cissus Quadrangularis",
    "Citric Acid",
    "Citrulline",
    "Clary Sage",
    "Clove",
    "Clubmoss",
    "Cnidium Monnieri",
    "Cocoa Extract",
    "Coenzyme Q10",
    "Coffee Pulp Extract",
    "Coleus Forskohlii",
    "Collagen",
    "Colostrum",
    "Coluracetam",
    "Conjugated Linoleic Acid",
    "Convolvulus Pluricaulis",
    "Copper",
    "Cordyceps",
    "Cotton Seed",
    "Creatine",
    "Creatinol O-Phosphate",
    "Cucurbita Pepo",
    "Curcumin",
    "Cyanidin",
    "Cyanocobalamin (Vitamin B12)",
    "D-Aspartic Acid",
    "D-Ribose",
    "D-Serine",
    "Dactylorhiza Hatagirea",
    "Damiana Leaf",
    "Dandelion",
    "Dang Shen",
    "Danshen",
    "Date Palm Pollen",
    "Dendrobium",
    "Devil's Claw",
    "DHEA",
    "Dihydroberberine",
    "Dill",
    "DIM",
    "DMAE",
    "Docosahexaenoic Acid",
    "Dong Quai",
    "Dwarf Morning Glory",
    "East Indian Globe Thistle",
    "ECA",
    "Ecdysteroids",
    "Echinacea",
    "Ecklonia Cava",
    "Elderberry",
    "Electric Nerve Stimulation",
    "Electrolytes",
    "Eleuthero",
    "Ellagic Acid",
    "Emollients",
    "Ephedrine",
    "Epigallocatechin Gallate",
    "Erythropoiesis-Stimulating Agents",
    "Essential Amino Acid (EAA)",
    "Essential Fatty Acid (EFA)",
    "Eucommia Bark",
    "European Raspberry",
    "Evening Primrose Oil",
    "Evodia Rutaecarpa",
    "Exogenous Ketones",
    "Fadogia Agrestis",
    "Fang Ji",
    "Fecal Transplant",
    "Fennel",
    "Fennel Essential Oil",
    "Fenugreek",
    "Fermented Foods",
    "Feverfew",
    "Fiber",
    "Fish Oil",
    "Flavanols",
    "Flavonols",
    "Flaxseed",
    "Folic Acid (Vitamin B9)",
    "Fructose",
    "GABA",
    "Gamma Oryzanol",
    "Garcinia",
    "Gelatin",
    "Genetically Modified Organisms",
    "Ginkgo Biloba",
    "Glucosamine",
    "Glucuronolactone",
    "Glutamine",
    "Glutathione",
    "Gluten",
    "Glycine",
    "GlyNAC",
    "Gotu Kola",
    "Gou-Teng",
    "Grains Of Paradise",
    "Grape Seed Extract",
    "Green Coffee Extract",
    "Green Tea Extract",
    "Griffonia Simplicifolia",
    "Guarana",
    "Guduchi",
    "Guggul",
    "Guided Imagery",
    "Gymnema Sylvestre",
    "Haninjin",
    "Haskap Berry",
    "Hederagenin",
    "Hemp Protein",
    "Hesperidin",
    "Hibiscus Macranthus",
    "Hibiscus Sabdariffa",
    "Higenamine",
    "Histidine",
    "HMB",
    "Hordenine",
    "Horny Goat Weed",
    "Horse Chestnut",
    "Huperzine A",
    "Hyaluronic Acid",
    "Hydroxyapatite",
    "Idebenone",
    "Inositol",
    "Insect Protein",
    "Inulin",
    "Iodine",
    "IP6",
    "Iron",
    "Isoleucine",
    "Japanese Catnip",
    "Japanese Knotweed",
    "Japanese Raisin Tree",
    "Jiaogulan",
    "Jojoba",
    "Jujube",
    "Kaempferol",
    "Kanna",
    "Kava",
    "Kelp",
    "King Of Bitters",
    "King Oyster",
    "Kokilaksha",
    "Korean Black Raspberry",
    "Kratom",
    "Krill Oil",
    "Ku Shen",
    "Kudzu",
    "Kutki",
    "L-Carnitine",
    "L-Cysteine",
    "L-Dopa",
    "L-Threonate",
    "L-Tyrosine",
    "Lactase Enzyme",
    "Lacticaseibacillus Paracasei",
    "Lactobacillus Acidophilus",
    "Lactobacillus Casei",
    "Lactobacillus Reuteri",
    "Lactoferrin",
    "Lactosucrose",
    "Laughter",
    "Laughter Yoga",
    "Lavender",
    "Lemon Balm",
    "Leucic Acid",
    "Leucine",
    "Licorice",
    "Limonene",
    "Lion's Mane",
    "Longan",
    "Loquat",
    "Luo Bu Ma",
    "Lutein",
    "Lycopene",
    "Lysine",
    "Maca",
    "Magnesium",
    "Magnolia Bark Extract",
    "Maitake",
    "Malabar Spinach",
    "Manganese",
    "Maral Root",
    "Massularia Acuminata",
    "Matured Hop Extract",
    "Medium-Chain Triglycerides",
    "Melatonin",
    "Menthol",
    "Methylliberine",
    "Microbiota Accessible Carbohydrates",
    "Microlactin",
    "Milk Protein",
    "Milk Thistle",
    "Minoxidil",
    "Mitoquinone Mesylate",
    "Molybdenum",
    "Mondo Grass",
    "Moringa",
    "Moro Orange Extract",
    "Motor Imagery",
    "Mouthwash",
    "MSM",
    "Mucuna Pruriens",
    "Muira Puama",
    "Mulberry Fruit Extract",
    "Multivitamin",
    "Mycoprotein",
    "Myofascial Release",
    "Myricetin",
    "N-Acetylcysteine",
    "N-Phenylacetyl-L-Prolylglycine Ethyl Ester",
    "N,N-Dimethyltryptamine",
    "Naringenin",
    "Nattokinase",
    "Neem",
    "Nefiracetam",
    "New Zealand Pine Bark Extract",
    "Niacin (Vitamin B3)",
    "Nicotinamide Adenine Dinucleotide",
    "Nicotinamide Mononucleotide",
    "Nicotinamide Riboside",
    "Nicotine",
    "Nitrate",
    "Nondigestible Fermentable Carbohydrates",
    "Nonnutritive Sweeteners",
    "Octopamine",
    "Oleamide",
    "Oleoylethanolamide",
    "Olive Leaf Extract",
    "Omega-3 Fatty Acids",
    "Omega-6 Fatty Acids",
    "Oral Immunotherapy",
    "Orange Peel",
    "Oregano",
    "Ornithine",
    "Oxaloacetate",
    "Oxiracetam",
    "Oxytropis Falcate",
    "Paederia Foetida",
    "Painting Therapy",
    "Palmatine",
    "Palmitoylethanolamide",
    "Panax Ginseng (Korean Ginseng)",
    "Panax Notoginseng",
    "Panax Quinquefolius (American Ginseng)",
    "Pantothenic Acid (Vitamin B5)",
    "Paraprobiotics",
    "Passionflower",
    "Patchouli",
    "Pea Protein",
    "Pedalium Murex",
    "Pelargonidin",
    "Peppermint",
    "Perilla",
    "Persicaria Minor",
    "Pet Ownership",
    "Phellodendron Amurense",
    "Phenylethylamine",
    "Phenylpiracetam",
    "Phlebodium Aureum",
    "Phosphatidylcholine",
    "Phosphatidylserine",
    "Phosphorus",
    "Piceatannol",
    "Pine Pollen",
    "Pinitol",
    "Piperine",
    "Piracetam",
    "Plant-Based Meats",
    "Plantago Major Seeds",
    "Policosanol",
    "Poly-Γ-Glutamic Acid",
    "Polygala Tenuifolia",
    "Pomegranate Seed Oil",
    "Potassium",
    "Powdered Fruits And Vegetables",
    "PQQ",
    "Pramiracetam",
    "Prebiotics",
    "Prenatal Vitamins",
    "PRL-8-53",
    "Probiotics",
    "Propolis",
    "Psyllium",
    "Pterostilbene",
    "Pueraria Mirifica",
    "Pumpkin Seed Extract",
    "Punarnava",
    "Punicalagins",
    "Purple Nutsedge",
    "Purslane Extract",
    "Pycnogenol",
    "Pygeum",
    "Pyridoxine (Vitamin B6)",
    "Pyritinol",
    "Pyruvate",
    "Quercetin",
    "Raspberry Ketone",
    "Rauwolscine",
    "Red Berry Powder",
    "Red Clover Extract",
    "Red Paprika Extract",
    "Red Spinach Extract",
    "Red Yeast Rice",
    "Reishi",
    "Resistant Starch",
    "Resveratrol",
    "Rhamnogalacturonan I",
    "Rhamnus Nakaharai",
    "Rhodiola Rosea",
    "Riboflavin (Vitamin B2)",
    "Rooibos",
    "Rose Essential Oil",
    "Rose Hip",
    "Roselle",
    "Rosemary Oil",
    "Rosmarinic Acid",
    "Royal Jelly",
    "Rutin",
    "S-Adenosylmethionine",
    "Sacred Lotus",
    "Safed Musli",
    "Safflower Oil",
    "Saffron",
    "Sage",
    "Salacia Reticulata",
    "Salidrosides",
    "Salt",
    "Sarcosine",
    "Saw Palmetto",
    "Schisandra",
    "Sea Buckthorn",
    "Selenium",
    "Senna",
    "Serrapeptase",
    "Sesamin",
    "Shatavari",
    "Shilajit",
    "Shivlingi",
    "Silica",
    "Silk Amino Acid (SAA)",
    "Silymarin",
    "Slippery Elm",
    "Society Garlic",
    "Sodium Bicarbonate",
    "Sodium Oligomannate",
    "Soy Isoflavones",
    "Soy Lecithin",
    "Soy Protein",
    "Spermidine",
    "Spikenard",
    "Spirulina",
    "Squalene",
    "St. John's Wort",
    "Stinging Nettle",
    "Sulbutiamine",
    "Sulforaphane",
    "Sunifiram",
    "Sweet Flag",
    "Synbiotics",
    "Tart Cherry Juice",
    "Taurine",
    "Tea (Camellia Sinensis)",
    "Tea Catechins",
    "Tea Tree Oil",
    "Terminalia Arjuna",
    "Terminalia Chebula",
    "Tetradecyl Thioacetic Acid",
    "Tetraselmis Chuii",
    "Thai Ginseng",
    "Theacrine",
    "Theaflavins",
    "Theanine",
    "Thermal Spring Water",
    "Thiamine (Vitamin B1)",
    "Thunder God Vine",
    "Tinospora Cordifolia",
    "Tongkat Ali",
    "Toothache Plant",
    "Torbangun",
    "Trehalose",
    "Tribulus Terrestris",
    "Trichopus Zeylanicus",
    "Tryptophan",
    "TUDCA",
    "Tulsi",
    "Turkey Tail Mushroom",
    "Type-II Collagen",
    "Umckaloabo",
    "Uridine",
    "Urolithin A",
    "Ursolic Acid",
    "Uva Ursi",
    "Valerian",
    "Valine",
    "Vanadium",
    "Velvet Antler",
    "Vinpocetine",
    "Violet Flower",
    "Vitamin A",
    "Vitamin C",
    "Vitamin D",
    "Vitamin E",
    "Vitamin K",
    "Vitamins E And C",
    "Whey Protein",
    "White Kidney Bean Extract",
    "White Mulberry",
    "Whole Coffee Fruit Extract",
    "Wild Celery Extract",
    "Wild Yam",
    "Yacon",
    "Yarrow",
    "Yeast Mannan",
    "Yohimbine",
    "Zeaxanthin",
    "Zinc",
    "ZMA"
]